INSERT INTO course (cid, ctitle) VALUES  ('COMP1', 'Advanced Topics in Artificial Intelligence');
INSERT INTO course (cid, ctitle) VALUES  ('COMP2', 'Computer Graphics and Visualization');
INSERT INTO course (cid, ctitle) VALUES  ('COMP3', 'Distributed Systems and Networking');
INSERT INTO course (cid, ctitle) VALUES  ('COMP4', 'Machine Learning for Data Analysis');
INSERT INTO course (cid, ctitle) VALUES  ('COMP5', 'Natural Language Processing');
INSERT INTO course (cid, ctitle) VALUES  ('COMP6', 'Advanced Topics in Computer Security');
INSERT INTO course (cid, ctitle) VALUES  ('COMP7', 'Web Application Development');
INSERT INTO course (cid, ctitle) VALUES  ('COMP8', 'High-Performance Computing');
INSERT INTO course (cid, ctitle) VALUES  ('COMP9', 'Software Engineering and Design Patterns');
INSERT INTO course (cid, ctitle) VALUES  ('COMP10', 'Cloud Computing Architecture and Infrastructure');
INSERT INTO course (cid, ctitle) VALUES  ('COMP11', 'Database Management Systems');
INSERT INTO course (cid, ctitle) VALUES  ('COMP12', 'Computer Vision and Image Processing');
INSERT INTO course (cid, ctitle) VALUES  ('COMP13', 'Mobile Application Development');
INSERT INTO course (cid, ctitle) VALUES  ('COMP14', 'Computer Networks and Communications');
INSERT INTO course (cid, ctitle) VALUES  ('COMP15', 'Cryptography and Network Security');
INSERT INTO course (cid, ctitle) VALUES  ('COMP16', 'Data Mining and Knowledge Discovery');
INSERT INTO course (cid, ctitle) VALUES  ('COMP17', 'Parallel and Distributed Algorithms');
INSERT INTO course (cid, ctitle) VALUES  ('COMP18', 'Human-Computer Interaction');
INSERT INTO course (cid, ctitle) VALUES  ('COMP19', 'Advanced Data Structures and Algorithms');
INSERT INTO course (cid, ctitle) VALUES  ('COMP20', 'Operating Systems and System Programming');
INSERT INTO course (cid, ctitle) VALUES  ('COMP21', 'Artificial Intelligence and Machine Learning Ethics');
INSERT INTO course (cid, ctitle) VALUES  ('COMP22', 'Advanced Topics in Human-Robot Interaction');
INSERT INTO course (cid, ctitle) VALUES  ('COMP23', 'Computer Systems Architecture');
INSERT INTO course (cid, ctitle) VALUES  ('COMP24', 'Embedded Systems Design and Programming');
INSERT INTO course (cid, ctitle) VALUES  ('COMP25', 'Quantum Computing and Quantum Information');
INSERT INTO course (cid, ctitle) VALUES  ('COMP26', 'Artificial Intelligence and Computer Vision for Robotics');
INSERT INTO course (cid, ctitle) VALUES  ('COMP27', 'Computational Science and Engineering');
INSERT INTO course (cid, ctitle) VALUES  ('COMP28', 'Intelligent Information Retrieval');
INSERT INTO course (cid, ctitle) VALUES  ('COMP29', 'Advanced Topics in Computer Vision');
INSERT INTO course (cid, ctitle) VALUES  ('COMP30', 'Formal Methods in Software Engineering');
INSERT INTO course (cid, ctitle) VALUES  ('COMP31', 'Computer Science and Society');
INSERT INTO course (cid, ctitle) VALUES  ('COMP32', 'Cybersecurity Threats and Defense');
INSERT INTO course (cid, ctitle) VALUES  ('COMP33', 'Computational Linguistics and Machine Translation');
INSERT INTO course (cid, ctitle) VALUES  ('COMP34', 'Robotics and Autonomous Systems');
INSERT INTO course (cid, ctitle) VALUES  ('COMP35', 'Programming Languages and Compilers');
INSERT INTO course (cid, ctitle) VALUES  ('COMP36', 'Software Testing and Verification');
INSERT INTO course (cid, ctitle) VALUES  ('COMP37', 'Advanced Computer Networks and Distributed Systems');
INSERT INTO course (cid, ctitle) VALUES  ('COMP38', 'Computer Science and Game Design');
INSERT INTO course (cid, ctitle) VALUES  ('COMP39', 'Machine Learning for Medical Applications');
INSERT INTO course (cid, ctitle) VALUES  ('COMP40', 'Advanced Topics in Blockchain and Cryptocurrencies');
INSERT INTO course (cid, ctitle) VALUES  ('MATH1', 'Introduction to Mathematical Analysis');
INSERT INTO course (cid, ctitle) VALUES  ('MATH2', 'Linear Algebra and Its Applications');
INSERT INTO course (cid, ctitle) VALUES  ('MATH3', 'Calculus and Differential Equations');
INSERT INTO course (cid, ctitle) VALUES  ('MATH4', 'Foundations of Mathematics');
INSERT INTO course (cid, ctitle) VALUES  ('MATH5', 'Probability and Statistics');
INSERT INTO course (cid, ctitle) VALUES  ('MATH6', 'Graph Theory and Combinatorics');
INSERT INTO course (cid, ctitle) VALUES  ('MATH7', 'Abstract Algebra and Number Theory');
INSERT INTO course (cid, ctitle) VALUES  ('MATH8', 'Topology and Geometry');
INSERT INTO course (cid, ctitle) VALUES  ('MATH9', 'Real Analysis and Measure Theory');
INSERT INTO course (cid, ctitle) VALUES  ('MATH10', 'Mathematical Modeling and Simulation');
INSERT INTO course (cid, ctitle) VALUES  ('MATH11', 'Partial Differential Equations');
INSERT INTO course (cid, ctitle) VALUES  ('MATH12', 'Numerical Methods and Scientific Computing');
INSERT INTO course (cid, ctitle) VALUES  ('MATH13', 'Discrete Mathematics and Logic');
INSERT INTO course (cid, ctitle) VALUES  ('MATH14', 'Game Theory and Applications');
INSERT INTO course (cid, ctitle) VALUES  ('MATH15', 'Algebraic Geometry and Cryptography');
INSERT INTO course (cid, ctitle) VALUES  ('MATH16', 'Functional Analysis and Applications');
INSERT INTO course (cid, ctitle) VALUES  ('MATH17', 'Complex Analysis and Applications');
INSERT INTO course (cid, ctitle) VALUES  ('MATH18', 'Mathematical Optimization and Operations Research');
INSERT INTO course (cid, ctitle) VALUES  ('MATH19', 'Stochastic Processes and Applications');
INSERT INTO course (cid, ctitle) VALUES  ('MATH20', 'Mathematical Finance and Risk Management');
INSERT INTO course (cid, ctitle) VALUES  ('MATH21', 'Nonlinear Differential Equations and Chaos Theory');
INSERT INTO course (cid, ctitle) VALUES  ('MATH22', 'Algebraic Topology and Homological Algebra');
INSERT INTO course (cid, ctitle) VALUES  ('MATH23', 'Dynamical Systems and Ergodic Theory');
INSERT INTO course (cid, ctitle) VALUES  ('MATH24', 'Probability Theory and Stochastic Analysis');
INSERT INTO course (cid, ctitle) VALUES  ('MATH25', 'Mathematics Education and Pedagogy');
INSERT INTO course (cid, ctitle) VALUES  ('MATH26', 'Harmonic Analysis and Wavelet Theory');
INSERT INTO course (cid, ctitle) VALUES  ('MATH27', 'Geometric Analysis and Partial Differential Equations');
INSERT INTO course (cid, ctitle) VALUES  ('MATH28', 'Mathematical Biology and Ecology');
INSERT INTO course (cid, ctitle) VALUES  ('MATH29', 'Coding Theory and Cryptography');
INSERT INTO course (cid, ctitle) VALUES  ('MATH30', 'Representation Theory and Lie Algebras');
INSERT INTO course (cid, ctitle) VALUES  ('MATH31', 'Knot Theory and Low-Dimensional Topology');
INSERT INTO course (cid, ctitle) VALUES  ('MATH32', 'Mathematical Physics and Quantum Mechanics');
INSERT INTO course (cid, ctitle) VALUES  ('MATH33', 'Analytic Number Theory and Diophantine Equations');
INSERT INTO course (cid, ctitle) VALUES  ('MATH34', 'Classical and Modern Geometry');
INSERT INTO course (cid, ctitle) VALUES  ('MATH35', 'Mathematical Logic and Model Theory');
INSERT INTO course (cid, ctitle) VALUES  ('MATH36', 'Algebraic Combinatorics and Combinatorial Optimization');
INSERT INTO course (cid, ctitle) VALUES  ('MATH37', 'Algebraic Number Theory and Arithmetic Geometry');
INSERT INTO course (cid, ctitle) VALUES  ('MATH38', 'Homotopy Theory and Algebraic Topology');
INSERT INTO course (cid, ctitle) VALUES  ('MATH39', 'Mathematical Structures and Algorithms');
INSERT INTO course (cid, ctitle) VALUES  ('MATH40', 'History of Mathematics and Foundations of Mathematical Thought');
INSERT INTO course (cid, ctitle) VALUES  ('BIO1', 'Cellular and Molecular Biology');
INSERT INTO course (cid, ctitle) VALUES  ('BIO2', 'Genetics and Genomics');
INSERT INTO course (cid, ctitle) VALUES  ('BIO3', 'Evolutionary Biology');
INSERT INTO course (cid, ctitle) VALUES  ('BIO4', 'Ecology and Conservation Biology');
INSERT INTO course (cid, ctitle) VALUES  ('BIO5', 'Microbiology and Immunology');
INSERT INTO course (cid, ctitle) VALUES  ('BIO6', 'Neurobiology and Behavior');
INSERT INTO course (cid, ctitle) VALUES  ('BIO7', 'Physiology and Biophysics');
INSERT INTO course (cid, ctitle) VALUES  ('BIO8', 'Developmental Biology');
INSERT INTO course (cid, ctitle) VALUES  ('BIO9', 'Biostatistics and Bioinformatics');
INSERT INTO course (cid, ctitle) VALUES  ('BIO10', 'Biochemistry and Biomolecular Structure');
INSERT INTO course (cid, ctitle) VALUES  ('BIO11', 'Plant Biology and Botany');
INSERT INTO course (cid, ctitle) VALUES  ('BIO12', 'Animal Behavior and Communication');
INSERT INTO course (cid, ctitle) VALUES  ('BIO13', 'Biotechnology and Genetic Engineering');
INSERT INTO course (cid, ctitle) VALUES  ('BIO14', 'Environmental Science and Sustainability');
INSERT INTO course (cid, ctitle) VALUES  ('BIO15', 'Systems Biology and Computational Biology');
INSERT INTO course (cid, ctitle) VALUES  ('BIO16', 'Human Anatomy and Physiology');
INSERT INTO course (cid, ctitle) VALUES  ('BIO17', 'Marine Biology and Oceanography');
INSERT INTO course (cid, ctitle) VALUES  ('BIO18', 'Medical Microbiology and Infectious Diseases');
INSERT INTO course (cid, ctitle) VALUES  ('BIO19', 'Cancer Biology and Oncology');
INSERT INTO course (cid, ctitle) VALUES  ('BIO20', 'Bioethics and Biomedical Ethics');
INSERT INTO course (cid, ctitle) VALUES  ('BIO21', 'Zoology and Animal Diversity');
INSERT INTO course (cid, ctitle) VALUES  ('BIO22', 'Biomedical Imaging and Biophotonics');
INSERT INTO course (cid, ctitle) VALUES  ('BIO23', 'Developmental Neurobiology and Aging');
INSERT INTO course (cid, ctitle) VALUES  ('BIO24', 'Biogeography and Biodiversity');
INSERT INTO course (cid, ctitle) VALUES  ('BIO25', 'Epigenetics and Gene Regulation');
INSERT INTO course (cid, ctitle) VALUES  ('BIO26', 'Immunology and Vaccinology');
INSERT INTO course (cid, ctitle) VALUES  ('BIO27', 'Molecular Genetics and Gene Editing');
INSERT INTO course (cid, ctitle) VALUES  ('BIO28', 'Metabolic Pathways and Bioenergetics');
INSERT INTO course (cid, ctitle) VALUES  ('BIO29', 'Plant Genetics and Epigenetics');
INSERT INTO course (cid, ctitle) VALUES  ('BIO30', 'Stem Cells and Regenerative Medicine');
INSERT INTO course (cid, ctitle) VALUES  ('BIO31', 'Evolutionary Ecology and Conservation Genetics');
INSERT INTO course (cid, ctitle) VALUES  ('BIO32', 'Molecular Medicine and Personalized Medicine');
INSERT INTO course (cid, ctitle) VALUES  ('BIO33', 'Bioprocessing and Biomanufacturing');
INSERT INTO course (cid, ctitle) VALUES  ('BIO34', 'Systems Neuroscience and Brain Function');
INSERT INTO course (cid, ctitle) VALUES  ('BIO35', 'Comparative Physiology and Adaptation');
INSERT INTO course (cid, ctitle) VALUES  ('BIO36', 'Aquatic Ecology and Limnology');
INSERT INTO course (cid, ctitle) VALUES  ('BIO37', 'Biochemistry of Metabolism and Signaling');
INSERT INTO course (cid, ctitle) VALUES  ('BIO38', 'Molecular Basis of Disease and Therapy');
INSERT INTO course (cid, ctitle) VALUES  ('BIO39', 'Plant-Microbe Interactions and Symbiosis');
INSERT INTO course (cid, ctitle) VALUES  ('BIO40', 'Ecological Modeling and Data Analysis');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS1', 'Classical Mechanics and Dynamics');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS2', 'Quantum Mechanics and Applications');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS3', 'Electromagnetism and Waves');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS4', 'Thermodynamics and Statistical Mechanics');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS5', 'Solid State Physics and Materials Science');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS6', 'Optics and Photonics');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS7', 'Nuclear and Particle Physics');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS8', 'Plasma Physics and Fusion Energy');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS9', 'Astrophysics and Cosmology');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS10', 'Biophysics and Medical Physics');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS11', 'Condensed Matter Physics and Nanoscience');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS12', 'Fluid Mechanics and Aerodynamics');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS13', 'Mathematical Methods in Physics');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS14', 'Experimental Techniques and Instrumentation');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS15', 'Relativity and Gravitation');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS16', 'Nonlinear Dynamics and Chaos Theory');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS17', 'Quantum Field Theory and Particle Physics');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS18', 'Quantum Computing and Information');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS19', 'Quantum Optics and Quantum Electronics');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS20', 'High Energy Astrophysics and Compact Objects');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS21', 'Quantum Gravity and Black Holes');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS22', 'Soft Matter Physics and Complex Systems');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS23', 'Atomic and Molecular Physics');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS24', 'Optical Spectroscopy and Imaging');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS25', 'Quantum Information Theory and Cryptography');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS26', 'Nanophotonics and Metamaterials');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS27', 'Particle Accelerators and High-Energy Physics');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS28', 'Physics of Energy and Environment');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS29', 'Neutron and X-ray Scattering');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS30', 'Superconductivity and Quantum Materials');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS31', 'Classical and Quantum Chaos in Dynamical Systems');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS32', 'Renewable Energy and Energy Conversion');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS33', 'Gravitational Waves and Cosmological Inflation');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS34', 'Quantum Computing and Quantum Algorithms');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS35', 'Environmental Physics and Climate Change');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS36', 'Photonics and Information Technology');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS37', 'Quantum Foundations and Interpretations');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS38', 'Theoretical Nuclear Physics and Applications');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS39', 'Atomic Physics and Quantum Optics');
INSERT INTO course (cid, ctitle) VALUES  ('PHYS40', 'Computational Physics and High-Performance Computing');
INSERT INTO course (cid, ctitle) VALUES  ('STAT1', 'Introduction to Probability Theory and Statistics');
INSERT INTO course (cid, ctitle) VALUES  ('STAT2', 'Statistical Inference and Hypothesis Testing');
INSERT INTO course (cid, ctitle) VALUES  ('STAT3', 'Linear Regression and Generalized Linear Models');
INSERT INTO course (cid, ctitle) VALUES  ('STAT4', 'Experimental Design and Analysis of Variance');
INSERT INTO course (cid, ctitle) VALUES  ('STAT5', 'Multivariate Statistical Analysis and Data Mining');
INSERT INTO course (cid, ctitle) VALUES  ('STAT6', 'Nonparametric Statistics and Robust Methods');
INSERT INTO course (cid, ctitle) VALUES  ('STAT7', 'Time Series Analysis and Forecasting');
INSERT INTO course (cid, ctitle) VALUES  ('STAT8', 'Statistical Learning and Data Science');
INSERT INTO course (cid, ctitle) VALUES  ('STAT9', 'Bayesian Statistics and Decision Theory');
INSERT INTO course (cid, ctitle) VALUES  ('STAT10', 'Categorical Data Analysis and Logistic Regression');
INSERT INTO course (cid, ctitle) VALUES  ('STAT11', 'Survival Analysis and Reliability');
INSERT INTO course (cid, ctitle) VALUES  ('STAT12', 'Introduction to Statistics 1');
INSERT INTO course (cid, ctitle) VALUES  ('STAT13', 'Introduction to Statistics 2');
INSERT INTO course (cid, ctitle) VALUES  ('STAT14', 'Introduction to Statistics 3');
INSERT INTO course (cid, ctitle) VALUES  ('STAT15', 'Introduction to Statistics 4');
INSERT INTO course (cid, ctitle) VALUES  ('STAT16', 'Spatial Statistics and Geostatistics');
INSERT INTO course (cid, ctitle) VALUES  ('STAT17', 'Statistical Computing and Graphics');
INSERT INTO course (cid, ctitle) VALUES  ('STAT18', 'Design of Experiments and Response Surface Methodology');
INSERT INTO course (cid, ctitle) VALUES  ('STAT19', 'Applied Regression Analysis and Mixed Models');
INSERT INTO course (cid, ctitle) VALUES  ('STAT20', 'Stochastic Processes and Queuing Theory');
INSERT INTO course (cid, ctitle) VALUES  ('STAT21', 'Statistical Genetics and Genomics');
INSERT INTO course (cid, ctitle) VALUES  ('STAT22', 'Sampling Theory and Survey Design');
INSERT INTO course (cid, ctitle) VALUES  ('STAT23', 'Financial Econometrics and Time Series Analysis');
INSERT INTO course (cid, ctitle) VALUES  ('STAT24', 'Experimental Methods in Social Science Research');
INSERT INTO course (cid, ctitle) VALUES  ('STAT25', 'Machine Learning and Neural Networks');
INSERT INTO course (cid, ctitle) VALUES  ('STAT26', 'Medical Statistics and Clinical Trials');
INSERT INTO course (cid, ctitle) VALUES  ('STAT27', 'Statistical Quality Control and Six Sigma');
INSERT INTO course (cid, ctitle) VALUES  ('STAT28', 'Statistical Process Control and Reliability Engineering');
INSERT INTO course (cid, ctitle) VALUES  ('STAT29', 'Big Data Analytics and High-Dimensional Data');
INSERT INTO course (cid, ctitle) VALUES  ('STAT30', 'Environmental Statistics and Risk Assessment');
INSERT INTO course (cid, ctitle) VALUES  ('STAT31', 'Advanced Bayesian Modeling and Computation');
INSERT INTO course (cid, ctitle) VALUES  ('STAT32', 'Statistical Programming and Data Visualization');
INSERT INTO course (cid, ctitle) VALUES  ('STAT33', 'Multilevel Modeling and Hierarchical Data Analysis');
INSERT INTO course (cid, ctitle) VALUES  ('STAT34', 'Spatial Econometrics and Geographic Information Systems');
INSERT INTO course (cid, ctitle) VALUES  ('STAT35', 'Business Analytics and Operations Research');
INSERT INTO course (cid, ctitle) VALUES  ('STAT36', 'Nonlinear Regression and Generalized Additive Models');
INSERT INTO course (cid, ctitle) VALUES  ('STAT37', 'Spatial and Temporal Modeling of Ecological Data');
INSERT INTO course (cid, ctitle) VALUES  ('STAT38', 'Applied Multivariate Analysis and Dimension Reduction');
INSERT INTO course (cid, ctitle) VALUES  ('STAT39', 'Meta-Analysis and Systematic Review');
INSERT INTO course (cid, ctitle) VALUES  ('STAT40', 'Statistical Disclosure Control and Confidentiality');