INSERT INTO course (cid, ctitle) VALUES  ('COMP1', 'Advanced Topics in Artificial Intelligence');
INSERT INTO course (cid, ctitle) VALUES  ('COMP2', 'Computer Graphics and Visualization');
INSERT INTO course (cid, ctitle) VALUES  ('COMP3', 'Distributed Systems and Networking');
INSERT INTO course (cid, ctitle) VALUES  ('COMP4', 'Machine Learning for Data Analysis');
INSERT INTO course (cid, ctitle) VALUES  ('COMP5', 'Natural Language Processing');
INSERT INTO course (cid, ctitle) VALUES  ('COMP6', 'Advanced Topics in Computer Security');
INSERT INTO course (cid, ctitle) VALUES  ('COMP7', 'Web Application Development');
INSERT INTO course (cid, ctitle) VALUES  ('COMP8', 'High-Performance Computing');
INSERT INTO course (cid, ctitle) VALUES  ('COMP9', 'Software Engineering and Design Patterns');
INSERT INTO course (cid, ctitle) VALUES  ('COMP10', 'Cloud Computing Architecture and Infrastructure');
INSERT INTO course (cid, ctitle) VALUES  ('COMP11', 'Database Management Systems');
INSERT INTO course (cid, ctitle) VALUES  ('COMP12', 'Computer Vision and Image Processing');
INSERT INTO course (cid, ctitle) VALUES  ('COMP13', 'Mobile Application Development');
INSERT INTO course (cid, ctitle) VALUES  ('COMP14', 'Computer Networks and Communications');
INSERT INTO course (cid, ctitle) VALUES  ('COMP15', 'Cryptography and Network Security');
INSERT INTO course (cid, ctitle) VALUES  ('COMP16', 'Data Mining and Knowledge Discovery');
INSERT INTO course (cid, ctitle) VALUES  ('COMP17', 'Parallel and Distributed Algorithms');
INSERT INTO course (cid, ctitle) VALUES  ('COMP18', 'Human-Computer Interaction');
INSERT INTO course (cid, ctitle) VALUES  ('COMP19', 'Advanced Data Structures and Algorithms');
INSERT INTO course (cid, ctitle) VALUES  ('COMP20', 'Operating Systems and System Programming');
INSERT INTO course (cid, ctitle) VALUES  ('COMP21', 'Artificial Intelligence and Machine Learning Ethics');
INSERT INTO course (cid, ctitle) VALUES  ('COMP22', 'Advanced Topics in Human-Robot Interaction');
INSERT INTO course (cid, ctitle) VALUES  ('COMP23', 'Computer Systems Architecture');
INSERT INTO course (cid, ctitle) VALUES  ('COMP24', 'Embedded Systems Design and Programming');
INSERT INTO course (cid, ctitle) VALUES  ('COMP25', 'Quantum Computing and Quantum Information');
INSERT INTO course (cid, ctitle) VALUES  ('COMP26', 'Artificial Intelligence and Computer Vision for Robotics');
INSERT INTO course (cid, ctitle) VALUES  ('COMP27', 'Computational Science and Engineering');
INSERT INTO course (cid, ctitle) VALUES  ('COMP28', 'Intelligent Information Retrieval');
INSERT INTO course (cid, ctitle) VALUES  ('COMP29', 'Advanced Topics in Computer Vision');
INSERT INTO course (cid, ctitle) VALUES  ('COMP30', 'Formal Methods in Software Engineering');
INSERT INTO course (cid, ctitle) VALUES  ('COMP31', 'Computer Science and Society');
INSERT INTO course (cid, ctitle) VALUES  ('COMP32', 'Cybersecurity Threats and Defense');
INSERT INTO course (cid, ctitle) VALUES  ('COMP33', 'Computational Linguistics and Machine Translation');
INSERT INTO course (cid, ctitle) VALUES  ('COMP34', 'Robotics and Autonomous Systems');
INSERT INTO course (cid, ctitle) VALUES  ('COMP35', 'Programming Languages and Compilers');
INSERT INTO course (cid, ctitle) VALUES  ('COMP36', 'Software Testing and Verification');
INSERT INTO course (cid, ctitle) VALUES  ('COMP37', 'Advanced Computer Networks and Distributed Systems');
INSERT INTO course (cid, ctitle) VALUES  ('COMP38', 'Computer Science and Game Design');
INSERT INTO course (cid, ctitle) VALUES  ('COMP39', 'Machine Learning for Medical Applications');
INSERT INTO course (cid, ctitle) VALUES  ('COMP40', 'Advanced Topics in Blockchain and Cryptocurrencies');